[IPCT1-308] List communities
impactMarket/mobile-app pull request #145
Opened 2021-08-02 08:04 UTC by obernardovieira

This PR fixes [IPCT1-308] at https://impactmarket.atlassian.net/browse/IPCT1-308

# Description

### Type of change

- Bug fix (fixes an issue)
- New feature (adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

- [ ] Manually
  - [ ] [BLU Advance L5](https://www.amazon.com/Advance-A390L-Unlocked-Phone-Camera/dp/B07Z6Q9NCZ/)
  - [ ] [SLIDE SP4514](https://www.amazon.com/dp/B06ZZ4KZF9?psc=1&ref=ppx_yo2_dt_b_product_details)
  - [ ] [Asus ZenFone 3 Max](https://www.tudocelular.com/Asus/fichas-tecnicas/n3260/Asus-ZenFone-3-Max.html)
  - [ ] Other 
- [ ] Automated

# Screenshots/Videos

2021-08-02 09:08 UTC, obernardovieira commented
![IMG_0006](https://user-images.githubusercontent.com/19441097/127835516-c982964d-f8f5-4efb-8a84-cd26aca776a2.PNG)

2021-08-09 14:04 UTC, obernardovieira commented
![IMG_0019](https://user-images.githubusercontent.com/19441097/128719333-2c9673f5-19be-4802-baad-ba9bfcff8fb9.PNG)

2021-08-09 14:20 UTC, Jonathansoufer requested changes

2021-08-09 14:20 UTC, Jonathansoufer commented on src/views/communities/List.tsx
> +                            UBI
Avoid using of hardcoded texts. Use i18n instead ;)

2021-08-09 14:20 UTC, Jonathansoufer commented on src/views/communities/List.tsx
> +    const [communtiesOrder, setCommuntiesOrder] = useState('bigger');
Maybe we should use constants instead of direct texts here, but not critical.

2021-08-12 08:19 UTC, obernardovieira commented
@Jonathansoufer ?

2021-08-16 10:10 UTC, Jonathansoufer approved these changes
LGTM! I didn't received a new request to review it, so that's the delay. Approved.

2021-08-16 10:12 UTC, merged